name: custom_response
description: Response class for Flutter projects
version: 0.0.1
repository: https://github.com/iemektar/custom_response

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: